FROM registry.cn-shanghai.aliyuncs.com/cedars/java8:latest

MAINTAINER sacher <sacherer@163.com>

ADD ./starting.sh /usr/local/bin/STARTING

RUN chmod 777 /usr/local/bin/STARTING

ENTRYPOINT STARTING && P
